# Change baseurl before deploy
baseURL = "https://drawn123.github.io/"
theme = "stack"
title = "Drawn123's Blog"

# Theme i18n support
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
hasCJKLanguage = true

[pagination]
    pagerSize = 5